### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yumi-jpn** [yumi-jpn/furima-33535#9]
# URL
https://furima-33535.herokuapp.com/

# Basic認証のIDとパスワード
 ID : admin
 pass : 2222

# 出品者用のメールアドレスとパスワード
 test@123
 123123abc

# 購入者用のメールアドレスとパスワード
 test@ezweb.ne.jp
 123123abc

# 購入用カードの番号・期限・セキュリティコード 
 4242424242424242
 1 / 31
 123

**Comment by naru6117** [comment]
@yumi-jpn さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正依頼箇所]

- [x] **ログイン状態の出品者が、URLを直接入力して自身の出品した商品購入ページに遷移しようとすると、トップページに遷移するようにしましょう！**

- [x] **出品者・出品者以外にかかわらず、ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するようにしましょう！**
現状、出品者がURLを直接入力すると、売却済み商品の商品情報編集ページへ遷移できてしまいます。



修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yumi-jpn** [comment]
ご確認ありがとうございます！

2箇所の修正いたしました。再度確認のほどお願い致します！

**Comment by snkw-works** [comment]
@yumi-jpn さん、再度ご提出いただきありがとうございます‼︎
動作の確認をしたところ、
> 出品者・出品者以外にかかわらず、ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するようにしましょう！

については修正が確認できました！ありがとうございます。
引き続き、以下、ご確認をお願い致します！

[修正依頼箇所]
- [x] **ログイン状態の出品者が、URLを直接入力して自身の出品した商品購入ページに遷移しようとすると、トップページに遷移するようにしましょう！**

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yumi-jpn** [comment]
1点目の修正できていませんでした、、
申し訳ございません！今度は修正できているかと思いますので再度お願い致します！

**Comment by snkw-works** [comment]
@yumi-jpn さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、引き続き修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品購入ページへ遷移しようとすると、"トップページ"に遷移するよう修正しましょう**
現在、ログイン状態のユーザー（出品者・出品者以外のユーザー両方）がURLを直接入力すると売却済み商品の商品購入ページへ遷移できてしまいます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yumi-jpn** [comment]
もっと重要な部分が抜けていました。失礼します。
修正いたしました！
またお手数ですが、確認のほどよろしくお願い致します！

**Comment by snkw-works** [comment]
@yumi-jpn さん、ご提出ありがとうございます‼︎
修正が確認でき、問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/54050089/106439987-a5e76780-64bb-11eb-85c8-18ea5481f03e.png)

**Comment by yumi-jpn** [comment]
至らない点も多くあった中、丁寧に確認いただきまして本当にありがとうございました！
自分の現状を目の当たりにして、これからはもっと自走できるエンジニアになれるよう、日々の学習を徹底しなければと痛感いたしました。
本当にありがとうございました！
